version: "3.7"

volumes:
  redis-local:
  postgres-local:

services:
  db:
    image: postgres:11.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=chat
    volumes:
      - postgres-local:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    restart: on-failure
    ports:
      - "5433:8081"
    environment:
      - DATABASE_URL=postgres://admin:secret@db:5432/chat?sslmode=disable
    depends_on:
      - db
    healthcheck:
      disable: true
